import Head from "next/head";

import { Nav } from "./../Components/Nav";
import { Banner } from "./../Components/Banner";
import { ProductList } from "./../Components/ProductList";
import { Footer } from "./../Components/Footer";

export default function Products() {
  return (
    <div>
      <Head>
        <title>Trendy House | Products</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <Banner image={"/images/product-banner.jpg"} />
      <main>
        <ProductList />
      </main>
      <Footer />
    </div>
  );
}
